# permissions for end users to view thingies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: thingy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cou-test
    app.kubernetes.io/part-of: cou-test
    app.kubernetes.io/managed-by: kustomize
  name: thingy-viewer-role
rules:
- apiGroups:
  - crap.tvs.io
  resources:
  - thingies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crap.tvs.io
  resources:
  - thingies/status
  verbs:
  - get
